project:
  type: book
  output-dir: docs

book:
  title: "test"
  author: "Norah Jones"
  date: "01-11-2024"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  # information
  favicon: "cover.png"

bibliography: references.bib

format:
  html:
    theme: cosmo
    
editor: visual

